"""Adversarial opponent relay — frame the opponent's message to be rebutted.

Anti-sycophancy (``docs/prds/anti-sycophancy.md`` §2 mechanism 1): "Separate
contexts + adversarial relay. The opponent's message is injected as *'Your
opponent argued: «…». Rebut it.'* — NOT as an agreeable peer turn." This module
implements that **relay framing** and wires it into the per-turn injection.

Two pieces:

* :func:`build_adversarial_relay` — the pure builder. It first **sanitises** the
  opponent's message through the security gatekeeper
  (:func:`~agent_debate.core.security.sanitize_untrusted_text`, PRD §5.7): the
  opponent text is generated by ANOTHER agent (untrusted), so it is normalised +
  injection-neutralised before being wrapped in :data:`ADVERSARIAL_RELAY_TEMPLATE`
  (the single source of the "«»" framing). This defends against one agent
  smuggling instructions into the other (defence-in-depth).
* :func:`relay_opponent_turn` — the per-turn helper. It injects BOTH the side
  anchor AND the framed (sanitised) opponent message as a single ``user`` turn
  into the agent's OWN :class:`~agent_debate.core.agents.context.AgentContext`,
  reusing :func:`~agent_debate.core.agents.anchoring.anchor_turn` (DRY — no
  duplicated anchor logic). The opponent's history is NEVER touched (5.4
  isolation), and the message enters as a ``user`` prompt to rebut — never as an
  agreeable ``assistant`` peer turn.

No external/network call — the security gatekeeper is pure text processing, so
the API gatekeeper (Epic 13) does not apply. The framing template and the
sanitiser source label are named constants (no hard-coded values).
"""

from __future__ import annotations

from agent_debate.core.agents.anchoring import anchor_turn
from agent_debate.core.agents.context import AgentContext
from agent_debate.core.security import sanitize_untrusted_text
from agent_debate.core.skills import DebateSide
from agent_debate.log import get_logger

_LOG = get_logger("agents")

#: Single source of truth for the adversarial relay framing (anti-sycophancy §2
#: mechanism 1). ``{message}`` is the *sanitised* opponent text, wrapped in "«»"
#: guillemets so it reads as quoted data, and an explicit order to rebut it — NOT
#: an agreeable peer turn. Written once here; never re-inlined at call sites.
ADVERSARIAL_RELAY_TEMPLATE = "Your opponent argued: «{message}». Rebut it."

#: ``source`` label recorded on the sanitiser's log event when it neutralises a
#: smuggled injection in the opponent's message (observability; a name, not a value).
RELAY_SANITISE_SOURCE = "opponent_relay"


def build_adversarial_relay(
    opponent_message: str,
    *,
    run_id: str | None = None,
) -> str:
    """Frame ``opponent_message`` adversarially after sanitising it (§2 mechanism 1).

    The opponent message is text produced by ANOTHER agent (untrusted), so it is
    first passed through :func:`~agent_debate.core.security.sanitize_untrusted_text`
    (normalise + injection-neutralise + length-cap) and only then wrapped in
    :data:`ADVERSARIAL_RELAY_TEMPLATE`. The result frames the message as a claim
    to rebut — never as an agreeable peer/assistant turn.

    Args:
        opponent_message: The opponent's last message (untrusted agent output).
        run_id: When set, the sanitiser logs a ``system`` event if it neutralises
            any smuggled injection in ``opponent_message`` (observability).

    Returns:
        The adversarially framed, sanitised relay string.
    """
    safe_message = sanitize_untrusted_text(
        opponent_message,
        source=RELAY_SANITISE_SOURCE,
        run_id=run_id,
    )
    return ADVERSARIAL_RELAY_TEMPLATE.format(message=safe_message)


def relay_opponent_turn(
    context: AgentContext,
    side: DebateSide,
    opponent_message: str,
    *,
    max_words: int | None = None,
    run_id: str | None = None,
) -> str:
    """Inject the side anchor + framed opponent relay as ONE ``user`` turn.

    Frames ``opponent_message`` via :func:`build_adversarial_relay` (sanitised,
    adversarial) and hands it to :func:`~agent_debate.core.agents.anchoring.
    anchor_turn` as the ``opponent_message`` so the side anchor and the relay
    combine into a single ``user`` turn appended to ``context`` — the agent's OWN
    history. The opponent's context is never touched (5.4 isolation), and the
    relay enters as an untrusted ``user`` prompt to rebut, not an ``assistant`` peer.

    Args:
        context: The debater's own :class:`AgentContext` to append into.
        side: The agent's assigned stance — used to pick the FOR/AGAINST anchor.
        opponent_message: The opponent's last message (untrusted agent output).
        max_words: Optional word limit included in the anchor (from config).
        run_id: Optional run id threaded to the sanitiser for injection logging.

    Returns:
        The exact text appended to ``context`` (anchor + framed relay).
    """
    framed = build_adversarial_relay(opponent_message, run_id=run_id)
    injected = anchor_turn(
        context,
        side,
        max_words=max_words,
        opponent_message=framed,
    )
    _LOG.debug("adversarial_relay_injected", identity=context.identity, side=side.value)
    return injected


__all__ = [
    "ADVERSARIAL_RELAY_TEMPLATE",
    "build_adversarial_relay",
    "relay_opponent_turn",
]
